import NavBar from "../components/nav/NavBar";
import Head from "next/head";
import { Inter } from "@next/font/google";
import Hm from "../components/Home/Home";
import Info from "@/components/Home/Info";
import style from "@/styles/index.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SociaLite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <main className={style.main}>
          <Info />
          <Hm />
        </main>
      </NavBar>
    </>
  );
}
