import NavBar from "@/components/nav/NavBar";
import Head from "next/head";
import { Inter } from "@next/font/google";
import About from "@/components/Home/About/About";
import About2 from "@/components/Home/About2/About2";
import style from "@/styles/index.module.scss";
import About3 from "@/components/Home/About3/About3";
import Footer from "@/components/Footer/Footer";
import Footer2 from "@/components/Footer/Footer2";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SociaLite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <main className={style.main}>
          <About />
          <About2 />
          <About3 />
          {/* <Footer /> */}
          <Footer2 />
        </main>
      </NavBar>
    </>
  );
}
